### ISSUE TITLE
hiiii

### ISSUE THREAD

**Issue by ahmadkamal1738** [joshuanianji/joshuanianji.github.io#80]
my gba sp screen doesnt work can u fix it pweeasseeeeee

**Comment by Mcnuget5** [comment]
user issue

**Comment by joshuanianji** [comment]
@ahmadkamal1738 pretty busy at the moment but feel free to submit a PR 👍

**Comment by ahmadkamal1738** [comment]
Personal record as in PR? My bench PR is 255

**Comment by joshuanianji** [comment]
Thanks for submitting your PR! Closing...
